[rtpengine]
table = 0
log-level = 3
interface = 127.0.0.1
listen-ng = 127.0.0.1:2223
listen-cli = 127.0.0.1:9900
xmlrpc-format = 2
b2b-url = http://trunks.ivozprovider.local:8002/RPC2
final-timeout = 10800
timeout = 60
tos = 184
pidfile = /var/run/rtpengine.pid
no-fallback = true
sip-source = true
recording-dir = /var/spool/rtpengine/
recording-method = proc
port-min = 13000
port-max = 19000
