[rtpengine-recording]
pidfile = /var/run/rtpengine-recording.pid
foreground = true
log-stderr = true
spool-dir = /var/spool/rtpengine
output-dir = /opt/irontec/ivozprovider/storage/ivozprovider_model_recordings.originalfile/
output-mixed = true
