#!/bin/bash

package=rtpengine
name=rtpengine
version=11.5.14

# make sure it's not running
if [ -x /etc/init.d/rtpengine ] ; then
	systemctl rtpengine stop || true
	rmmod "xt_RTPENGINE" 2>/dev/null || true
fi


#DEBHELPER#

:
